<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="0" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Couldn't create screenshot]]>
    </line>
    <line>
      <![CDATA[Connection refused: connect]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="2062" started-at="2013-04-29T21:39:25Z" finished-at="2013-04-29T21:39:27Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="2062" started-at="2013-04-29T21:39:25Z" finished-at="2013-04-29T21:39:27Z">
      <class name="com.selenium.slx.mobileclient.ExpTestNG">
        <test-method status="PASS" signature="attachScreenshotListener(java.lang.String, java.lang.String, org.testng.ITestContext)[pri:0, instance:com.selenium.slx.mobileclient.ExpTestNG@b01999]" name="attachScreenshotListener" is-config="true" duration-ms="48" started-at="2013-04-29T14:39:25Z" finished-at="2013-04-29T14:39:25Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[localhost]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[4444]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[org.testng.TestRunner@81876b]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- attachScreenshotListener -->
        <test-method status="FAIL" signature="setUp(java.lang.String, java.lang.String)[pri:0, instance:com.selenium.slx.mobileclient.ExpTestNG@b01999]" name="setUp" is-config="true" duration-ms="0" started-at="2013-04-29T14:39:25Z" finished-at="2013-04-29T14:39:25Z">
          <params>
            <param index="0">
              <value is-null="true"/>
            </param>
            <param index="1">
              <value is-null="true"/>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Could not contact Selenium Server; have you started it on 'localhost:4444' ?
Read more at http://seleniumhq.org/projects/remote-control/not-started.html
Connection refused: connect]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Could not contact Selenium Server; have you started it on 'localhost:4444' ?
Read more at http://seleniumhq.org/projects/remote-control/not-started.html
Connection refused: connect
	at com.thoughtworks.selenium.DefaultSelenium.start(DefaultSelenium.java:104)
	at com.thoughtworks.selenium.SeleneseTestBase.setUp(SeleneseTestBase.java:134)
	at com.thoughtworks.selenium.SeleneseTestBase.setUp(SeleneseTestBase.java:103)
	at com.thoughtworks.selenium.SeleneseTestNgHelper.setUp(SeleneseTestNgHelper.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:641)
	at org.testng.TestRunner.run(TestRunner.java:609)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
            <line>
              <![CDATA[Couldn't create screenshot]]>
            </line>
            <line>
              <![CDATA[Connection refused: connect]]>
            </line>
          </reporter-output>
        </test-method> <!-- setUp -->
      </class> <!-- com.selenium.slx.mobileclient.ExpTestNG -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
